name = "MinecraftTogether"
author = "luochen1990@gmail.com"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c0ccf616f11e6009da1b5c260a6f53172a66317744128cdaa4a5b3d9b81542d2"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
