name = "MinecraftTogether"
author = "luochen1990@gmail.com"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9555468dadbba3a8cbdf24766fd89f18ee3a8cd6840a82f613370eba164921db"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
