name = "MinecraftTogether"
author = "luochen1990@gmail.com"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce6e7295cf772578171c6bbefe806b49207008e8b22123825d3bd69a032e8d13"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
