name = "MinecraftTogether"
author = "luochen1990@gmail.com"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a421d5117ce29edc75654c17bd53fd3eeab40777db78b5f1bfe7e7bbc176a87"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
