name = "MinecraftTogether"
author = "luochen1990@gmail.com"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b15dd2ecd5626178305e2a340cfbf3b73753397bac24659a11bd3821980c5a22"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
